### ISSUE TITLE
Tool stops after checking all thumbnails with this error.

### ISSUE THREAD

**Issue by CaptainHIT** [maforget/Delete-RetroArch-Unneeded-Thumbnails#1]
There are some folders I created for No-Intro roms. The core for these is the same and Retroarch downloads thumbnails only into the "Commodore - 64" folder. That's why the tool exits with an error. Could this be skipped somehow?

Checking all thumbnails

Unhandled exception: System.IO.DirectoryNotFoundException: Part of the path "c:\RetroArch-Win64\thumbnails\Commodore - 64 (PP)" could not be found.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileSystemEnumerableIterator`1.CommonInit()
   bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   bei System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   bei Retroarch_Delete_Unneeded_Thumbnails.Thumbnail.GetUnassociatedImages(List`1 playlists)
   bei Retroarch_Delete_Unneeded_Thumbnails.Program.Main(String[] args)

[cmd output.txt](https://github.com/maforget/Delete-RetroArch-Unneeded-Thumbnails/files/7872816/cmd.output.txt)

**Comment by CaptainHIT** [comment]
There is a Uzebox rom folder and playlist, but no Uzebox thumbnails folder. The tool still quits with the same error. Could just skip looking for it.

**Comment by CaptainHIT** [comment]
And maybe this tool could be feature of Retroarch itself maybe? A simple enrty in

Settings -> Playlists -> Remove unused thumbnails

**Comment by maforget** [comment]
> And maybe this tool could be feature of Retroarch itself maybe? A simple enrty in
> 
> Settings -> Playlists -> Remove unused thumbnails

You need to ask the Retroarch team for that, I have no affiliation with them.

I added a check if the corresponding folder doesn't exists, so it won't crash. But the reason for the tool is to also check for files that don't have thumbnails, so you will get a big list for the non existent folders. 57a7e05ba0f099b3e22a73433de9b2a443ae5d41 Check Release v1.4
